---
abstract: 'Read and write PNG files'
author:
  - 'Ben Bullock <bkb@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Image-PNG
no_index:
  directory:
    - t
    - inc
    - tmpl
    - build
requires:
  Image::PNG::Libpng: 0.27
  perl: 5.008001
resources:
  MailingList: http://groups.google.com/group/perlimagepng
  bugtracker: https://github.com/benkasminbullock/Image-PNG/issues
  repository: https://github.com/benkasminbullock/Image-PNG
version: 0.20_02
