--- #YAML:1.0
name: 'Image::PNG'
version: 0.07
abstract: 'Read and write PNG (Portable Network Graphics) files'
author:
    - Ben Bullock <bkb@cpan.org>
license: perl
distribution_type: module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
        - tmpl
        - build
