--- #YAML:1.0
name: 'Image::PNG'
version: 0.13
abstract: 'Read and write PNG files'
author:
    - Ben Bullock <bkb@cpan.org>
license: perl
distribution_type: module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:  {}
no_index:
    directory:
        - t
        - inc
        - tmpl
        - build
resources:
    MailingList: http://groups.google.com/group/perlimagepng
    bugtracker: https://github.com/benkasminbullock/Image-PNG/issues
    repository: https://github.com/benkasminbullock/Image-PNG
